version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: DockerFile  # or rename to Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://mongo:27017/mydb
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  node_modules:
  mongo_data:
